SkiArea.create(ski_area_name: '49 Degrees North ', latitude: 48.3011, longitude: -117.5629, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Abenaki Ski Area ', latitude: 43.6115, longitude: -71.2291, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Afton Alps ', latitude: 44.8577, longitude: -92.7878, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alpental', latitude: 47.4431678, longitude: -121.4295388, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alpine Meadows ', latitude: 39.1785, longitude: -120.2277, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alpine Mountain Ski & Ride Center ', latitude: 41.1133, longitude: -75.2256, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alpine Valley ', latitude: 42.738, longitude: -88.4339, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alpine Valley Resort ', latitude: 42.7358, longitude: -88.4281, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alpine Valley Ski Area ', latitude: 42.7358, longitude: -88.4281, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alta ', latitude: 40.5888, longitude: -111.638, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alta Sierra ', latitude: 39.1416, longitude: -121.0538, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Alyeska ', latitude: 64.2008, longitude: -149.4937, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Andes Tower Hills ', latitude: 45.851, longitude: -95.6305, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Angel Fire Resort ', latitude: 36.3877, longitude: -105.2733, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Anthony Lakes ', latitude: 44.9994, longitude: -118.0542, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Appalachian Ski Mountain ', latitude: 36.1744, longitude: -81.6626, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Arapahoe Basin ', latitude: 39.6425, longitude: -105.8719, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Arctic Valley ', latitude: 61.2467, longitude: -149.5349, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Arizona Snowbowl ', latitude: 35.3309, longitude: -111.7103, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Arrowhead ', latitude: 35.3309, longitude: -111.7103, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Aspen Highlands', latitude: 39.1823, longitude: -106.8555, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Aspen Mountain', latitude: 39.1863, longitude: -106.8182, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Attitash ', latitude: 44.0828, longitude: -71.2294, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Badger Mountain ', latitude: 47.5836, longitude: -120.1794, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Badger Pass ', latitude: 37.6623, longitude: -119.6634, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Baker Mountain ', latitude: 48.7767, longitude: -121.8144, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bald Mountain ', latitude: 41.1209, longitude: -74.2001, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bear Creek Mountain Resort ', latitude: 40.4797, longitude: -75.6216, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bear Mountain ', latitude: 41.3129, longitude: -74.0063, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bear Paw Ski Bowl', latitude: 48.165, longitude: -109.6701, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bear Valley ', latitude: 38.4646, longitude: -120.0399, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Beartown Ski Area ', latitude: 44.7641, longitude: -73.5838, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Beaver Creek Resort ', latitude: 39.6043, longitude: -106.5167, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Beaver Mountain ', latitude: 41.9681, longitude: -111.5441, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Belleayre Ski Center ', latitude: 42.1322, longitude: -74.5053, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Berkshire East Ski Resort ', latitude: 42.6211, longitude: -72.8771, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Big Creek Ski Area ', latitude: 48.4831, longitude: -114.3582, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Big Horn ', latitude: 44.6036, longitude: -108.0941, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Big Rock ', latitude: 46.5224, longitude: -67.8289, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Big Sky ', latitude: 45.2618, longitude: -111.308, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Big Squaw ', latitude: 45.5067, longitude: -69.702, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Big Tupper Ski Area ', latitude: 44.1694, longitude: -74.4794, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Black Mountain ', latitude: 35.6179, longitude: -82.3212, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Black Mountain of Maine ', latitude: 44.577, longitude: -70.6133, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Blackjack Ski Resort ', latitude: 46.5042, longitude: -89.9982, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Blacktail Mountain ', latitude: 48.0129, longitude: -114.2382, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Blandford Ski Area ', latitude: 42.1958, longitude: -72.9166, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Blue Hills Ski Area ', latitude: 42.216, longitude: -71.1191, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Blue Mountain Ski Area ', latitude: 40.8107, longitude: -75.5209, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bogus Basin ', latitude: 43.7641, longitude: -116.1026, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bolton Valley Resort ', latitude: 44.421, longitude: -72.8503, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Boreal Mountain ', latitude: 39.3365, longitude: -120.3498, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Boston Mills/Brandywine Ski Resort ', latitude: 41.2641, longitude: -81.5632, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bottineau Winter Park ', latitude: 48.9512, longitude: -100.4775, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bousquet Ski Area ', latitude: 42.4192, longitude: -73.2771, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Boyce Park ', latitude: 40.467, longitude: -79.7443, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Boyne Highlands Resort ', latitude: 45.4708, longitude: -84.9354, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Boyne Mountain ', latitude: 45.1629, longitude: -84.9301, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Breckenridge Ski Resort ', latitude: 39.48, longitude: -106.067, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bretton Woods ', latitude: 44.2583, longitude: -71.4433, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Brian Head ', latitude: 37.7021, longitude: -112.8499, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bridger Bowl ', latitude: 45.8174, longitude: -110.8966, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Brighton ', latitude: 40.598, longitude: -111.5832, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bristol Mountain Ski Resort ', latitude: 42.7453, longitude: -77.4043, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bromley Mountain ', latitude: 43.2279, longitude: -72.9387, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Brundage Mountain ', latitude: 45.0054, longitude: -116.1544, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Bryce Resort ', latitude: 38.8175, longitude: -78.7656, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Buck Hill ', latitude: 38.8175, longitude: -78.7656, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Buckhorn Ski Club ', latitude: 34.3419, longitude: -117.9197, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Buena Vista Ski Area ', latitude: 47.658, longitude: -94.8789, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Buffalo Ski Club ', latitude: 42.681, longitude: -78.692, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Burke Mountain ', latitude: 44.5712, longitude: -71.8923, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Buttermilk', latitude: 39.2058, longitude: -106.8605, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Butternut ', latitude: 46.013, longitude: -90.4904, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Caberfae Peaks Ski & Golf Resort ', latitude: 44.2447, longitude: -85.7206, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Camden Snow Bowl ', latitude: 44.2173, longitude: -69.1347, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Camelback Ski Area ', latitude: 41.0512, longitude: -75.3555, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Camp 10 ', latitude: 44.1527, longitude: -87.9395, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Campgaw Mountain ', latitude: 41.0586, longitude: -74.195, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Campton Mountain ', latitude: 43.8473, longitude: -71.5806, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Canaan Valley Resort ', latitude: 39.0084, longitude: -79.4385, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cannon Mountain ', latitude: 44.1565, longitude: -71.6984, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cannonsburg Ski Area ', latitude: 43.0541, longitude: -85.5012, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cascade Mountain ', latitude: 43.5037, longitude: -89.5173, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cataloochee Ski Area ', latitude: 35.5624, longitude: -83.09, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Catamount Ski Area ', latitude: 42.1691, longitude: -73.4769, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Challenge Mountain ', latitude: 45.2046, longitude: -84.9983, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cherry Peak Resort ', latitude: 41.9263, longitude: -111.7564, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Chestnut Mountain Resort ', latitude: 42.319, longitude: -90.3938, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'China Peak ', latitude: 37.2365, longitude: -119.1573, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Christie Mountain ', latitude: 45.5091, longitude: -91.3808, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Christmas Mountain Village ', latitude: 43.609, longitude: -89.8603, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cooper Spur ', latitude: 45.4116, longitude: -121.6058, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Copper Mountain Resort ', latitude: 39.5021, longitude: -106.151, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cottonwood Butte ', latitude: 46.0756, longitude: -116.4526, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Cranmore Mountain Resort ', latitude: 44.0565, longitude: -71.1102, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Crested Butte Mountain Resort ', latitude: 38.8991, longitude: -106.9654, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Crotched Mountain ', latitude: 42.9984, longitude: -71.8737, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Crystal Mountain ', latitude: 46.9282, longitude: -121.5045, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Crystal Ridge ', latitude: 46.9282, longitude: -121.5045, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Dartmouth Skiway ', latitude: 43.7877, longitude: -72.0995, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Deer Mountain ', latitude: 40.3794, longitude: -105.5847, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Deer Valley ', latitude: 40.6374, longitude: -111.4783, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Detroit Mountain ', latitude: 46.8132, longitude: -95.7834, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Devils Head Resort ', latitude: 43.418, longitude: -89.6269, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Diamond Peak ', latitude: 39.2545, longitude: -119.9139, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Discovery ', latitude: 46.2496, longitude: -113.2385, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Dodge Ridge ', latitude: 38.1899, longitude: -119.9558, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Donner Ski Ranch ', latitude: 39.3177, longitude: -120.3303, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Dry Hill Ski Area ', latitude: 43.9312, longitude: -75.9018, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Eagle Point Ski Resort ', latitude: 38.3203, longitude: -112.3839, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Eagle Rock Resort ', latitude: 40.9203, longitude: -76.0969, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Eaglecrest ', latitude: 58.2675, longitude: -134.514, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Echo Mountain Resort ', latitude: 39.6846, longitude: -105.5194, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Echo Valley ', latitude: 47.9357, longitude: -120.0554, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Eldora Mountain Resort ', latitude: 39.9372, longitude: -105.5827, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Elk Mountain ', latitude: 41.6894, longitude: -106.4141, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Elk Ridge Ski Area ', latitude: 35.2147, longitude: -112.1922, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ferguson Ridge ', latitude: 45.2822, longitude: -117.1126, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Fox Hill Ski Area ', latitude: 43.375, longitude: -88.2521, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Frost Fire ', latitude: 48.9115, longitude: -98.0676, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Garland Resort ', latitude: 44.8186, longitude: -84.3098, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Giants Ridge ', latitude: 47.5765, longitude: -92.3032, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Gore Mountain ', latitude: 43.6733, longitude: -74.0068, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Grand Targhee ', latitude: 43.7871, longitude: -110.9593, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Granite Gorge ', latitude: 42.971, longitude: -72.212, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Granite Peak ', latitude: 45.1633, longitude: -109.808, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Granlibakken ', latitude: 39.1562, longitude: -120.1544, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Great Bear ', latitude: 34.2267, longitude: -116.8602, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Great Divide ', latitude: 46.7531, longitude: -112.3135, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Greek Peak ', latitude: 42.5083, longitude: -76.1454, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Gunstock Mountain Resort ', latitude: 43.5411, longitude: -71.3629, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Heavenly Mountain ', latitude: 38.9353, longitude: -119.94, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hermon Mountain ', latitude: 44.7808, longitude: -68.9573, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hickory Hills Ski Area ', latitude: 44.7688, longitude: -85.6662, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hickory Ski Center ', latitude: 43.4744, longitude: -73.8173, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hidden Valley ', latitude: 40.1068, longitude: -75.378, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hidden Valley Four Seasons Resort ', latitude: 38.5353, longitude: -90.6507, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hogadon ', latitude: 42.7453, longitude: -106.339, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Holiday Mountain Ski & Fun ', latitude: 41.6296, longitude: -74.6145, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Holiday Valley ', latitude: 42.2626, longitude: -78.6674, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Holimont ', latitude: 42.2732, longitude: -78.6891, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Homewood Mountain ', latitude: 39.0856, longitude: -120.1605, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hoodoo ', latitude: 44.4088, longitude: -121.8715, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Howelsen Hill Ski Area ', latitude: 40.4834, longitude: -106.838, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Huff Hills ', latitude: 46.6269, longitude: -100.7233, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hunter Mountain ', latitude: 42.2044, longitude: -74.2105, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hurricane Ridge ', latitude: 47.9331, longitude: -123.4096, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Hyland Ski and Snowboard Area ', latitude: 44.8436, longitude: -93.3636, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Indianhead Mountain Resort ', latitude: 46.5003, longitude: -89.9709, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Jack Frost Big Boulder ', latitude: 41.11, longitude: -75.6512, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Jackson Hole ', latitude: 43.4799, longitude: -110.7624, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Jay Peak Resort ', latitude: 44.938, longitude: -72.5045, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Jiminy Peak ', latitude: 42.5554, longitude: -73.2922, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'June Mountain ', latitude: 37.7679, longitude: -119.0906, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Kelly Canyon ', latitude: 43.6445, longitude: -111.6309, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Kendall Mountain Ski Area ', latitude: 37.81135, longitude: -107.65652, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Kettlebowl ', latitude: 45.2718, longitude: -88.9014, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Keyes Peak ', latitude: 45.8957, longitude: -88.2995, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Keystone Resort ', latitude: 39.6084, longitude: -105.9437, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Killington Ski Resort ', latitude: 43.626, longitude: -72.7967, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'King Pine ', latitude: 43.8681, longitude: -71.0889, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Kirkwood Mountain ', latitude: 38.6848, longitude: -120.0652, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Kissing Bridge ', latitude: 42.6002, longitude: -78.6527, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Kratka Ridge ', latitude: 34.3494, longitude: -117.889, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Labrador Mountain ', latitude: 42.7418, longitude: -76.0302, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lake City Ski Hill', latitude: 38.011, longitude: -107.3116, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Laurel Mountain Ski Resort ', latitude: 40.1635, longitude: -79.1654, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Leavenworth Ski Hill ', latitude: 47.6141, longitude: -120.6687, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lee Canyon (Ski and Snowboard Resort) ', latitude: 36.3037, longitude: -115.6796, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Liberty Mountain Resort ', latitude: 39.7637, longitude: -77.3755, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Little Ski Hill ', latitude: 44.9301, longitude: -116.1625, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Little Switzerland Ski Area ', latitude: 43.338, longitude: -88.2789, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lonesome Pine Trails ', latitude: 47.246, longitude: -68.5945, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lookout Pass ', latitude: 47.456, longitude: -115.6973, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Loon Mountain ', latitude: 44.036, longitude: -71.6214, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lost Trail Powder Mountain ', latitude: 45.6935, longitude: -113.9501, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lost Valley ', latitude: 44.1341, longitude: -70.2824, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Loup Loup Ski Bowl ', latitude: 48.3944, longitude: -119.911, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Loveland Ski Area ', latitude: 39.68, longitude: -105.8979, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lutsen Mountains ', latitude: 47.6637, longitude: -90.7136, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Lyndon Outing Club ', latitude: 44.5333, longitude: -71.9872, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mad River Glen ', latitude: 44.2025, longitude: -72.9175, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mad River Mountain ', latitude: 40.3181, longitude: -83.6777, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Magic Mountain ', latitude: 43.2017, longitude: -72.7726, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mammoth Mountain ', latitude: 37.6308, longitude: -119.0326, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Marquette Mountain ', latitude: 46.5082, longitude: -87.4208, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Massanutten Ski Resort ', latitude: 38.4066, longitude: -78.7161, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Maverick Mountain ', latitude: 45.4339, longitude: -113.1286, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'McCauley Mountain ', latitude: 43.6926, longitude: -74.9613, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'McIntyre Ski Area ', latitude: 43.0066, longitude: -71.4417, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Meany Lodge ', latitude: 47.2803, longitude: -121.3201, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Middlebury College Snow Bowl ', latitude: 43.9392, longitude: -72.9576, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mission Ridge ', latitude: 47.2925, longitude: -120.3999, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mohawk Mountain Ski Area ', latitude: 41.8382, longitude: -73.3151, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Monarch Ski Area ', latitude: 38.5122, longitude: -106.3322, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mont Ripley Ski Resort ', latitude: 47.1276, longitude: -88.561, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Montage Mountain Ski Resort ', latitude: 41.3512, longitude: -75.6629, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Montana Snowbowl ', latitude: 47.0144, longitude: -113.9996, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Moonlight Basin ', latitude: 45.295, longitude: -111.4216, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Moose Mountain ', latitude: 64.9406, longitude: -147.9906, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Abram ', latitude: 44.3798, longitude: -70.7069, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Ashland ', latitude: 42.0817, longitude: -122.7048, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Bachelor ', latitude: 43.9972, longitude: -121.4052, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Baldy Ski Lifts ', latitude: 34.2701, longitude: -117.6219, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Bohemia ', latitude: 47.3886, longitude: -88.0222, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Eyak ', latitude: 60.55, longitude: -145.75, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Greylock Ski Club ', latitude: 42.6342, longitude: -73.2152, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Hood Meadows ', latitude: 45.3318, longitude: -121.6652, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Hood Skibowl ', latitude: 45.3017, longitude: -121.7725, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Itasca ', latitude: 47.2855, longitude: -93.4475, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Kato ', latitude: 44.1331, longitude: -94.0334, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Lemmon Ski Valley ', latitude: 32.4475, longitude: -110.7817, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Peter Ski Area ', latitude: 32.4475, longitude: -110.7817, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Prospect ', latitude: 42.0664, longitude: -87.9373, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Rose ', latitude: 39.3284, longitude: -119.8854, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Shasta Ski Park ', latitude: 41.3211, longitude: -122.2035, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Snow ', latitude: 42.9602, longitude: -72.9204, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Southington ', latitude: 41.5821, longitude: -72.9249, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Spokane ', latitude: 47.9213, longitude: -117.1141, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Sunapee Resort ', latitude: 43.3319, longitude: -72.0801, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mount Waterman ', latitude: 34.3493, longitude: -117.9288, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mountain High ', latitude: 34.3769, longitude: -117.6915, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mountain View at Edinboro ', latitude: 41.851, longitude: -80.0703, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. Ashwabay ', latitude: 46.7772, longitude: -90.8946, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. Baker ', latitude: 48.8573, longitude: -121.6667, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. Brighton Ski Resort ', latitude: 42.5408, longitude: -83.8116, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. Holiday ', latitude: 44.7416, longitude: -85.5146, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. Holly Ski and Snowboard Resort ', latitude: 42.8312, longitude: -83.5621, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. LaCrosse ', latitude: 43.7436, longitude: -91.183, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Mt. Zion Ski Area ', latitude: 46.4742, longitude: -90.163, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Nashoba Valley Ski Area ', latitude: 42.5426, longitude: -71.445, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Navarino Slopes ', latitude: 44.6104, longitude: -88.5855, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Nordic Mountain ', latitude: 44.1214, longitude: -89.1813, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Nordic Valley ', latitude: 41.3104, longitude: -111.8648, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Northstar California ', latitude: 39.2746, longitude: -120.1211, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Norway Mountain Ski and Snowboard Resort ', latitude: 45.7895, longitude: -87.8699, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: "Nub's Nob ", latitude: 45.4718, longitude: -84.9041, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Nutt Hill ', latitude: 41.2317, longitude: -73.6819, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ober Gatlinburg ', latitude: 35.7035, longitude: -83.5578, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Oglebay Resort ', latitude: 40.1048, longitude: -80.6594, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Okemo Mountain ', latitude: 43.4018, longitude: -72.717, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Otis Ridge ', latitude: 42.1964, longitude: -73.0984, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Otsego Club & Resort ', latitude: 45.0277, longitude: -84.6553, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pajarito Mountain ', latitude: 35.895, longitude: -106.3909, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Paoli Peaks ', latitude: 38.5556, longitude: -86.5122, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Park City Mountain Resort ', latitude: 40.6514, longitude: -111.508, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pats Peak ', latitude: 43.164, longitude: -71.7977, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pebble Creek ', latitude: 42.7786, longitude: -112.1593, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: "Peek'n Peak ", latitude: 42.0625, longitude: -79.73667, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Perfect North Slopes ', latitude: 39.1475, longitude: -84.8857, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Petoskey Winter Sports Park ', latitude: 45.3763, longitude: -84.9455, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pico Mountain ', latitude: 43.6621, longitude: -72.8425, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pine Creek ', latitude: 42.103, longitude: -110.8288, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pine Knob Ski Resort ', latitude: 42.7423, longitude: -83.3672, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pine Mountain Resort ', latitude: 45.8393, longitude: -88.0886, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pines Peak ', latitude: 38.8409, longitude: -105.0423, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pinnacle Ski Club ', latitude: 41.0445, longitude: -73.5247, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Plattekill Mountain ', latitude: 42.2903, longitude: -74.6532, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Plymouth Notch ', latitude: 43.5303, longitude: -72.7386, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Pomerelle ', latitude: 42.318, longitude: -113.6078, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Porcupine Mountains ', latitude: 46.8196, longitude: -89.6484, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Powder Mountain ', latitude: 41.379, longitude: -111.7807, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Powder Ridge ', latitude: 41.5005, longitude: -72.7407, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Powderhorn Resort ', latitude: 39.0694, longitude: -108.1507, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Purgatory Resort ', latitude: 37.6263, longitude: -107.8337, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Quoggy Jo ', latitude: 46.7222, longitude: -67.9293, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ragged Mountain ', latitude: 43.4854, longitude: -71.8421, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Red Hill Ski Club ', latitude: 43.7493, longitude: -71.4161, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Red Lodge Mountain ', latitude: 45.1908, longitude: -109.3364, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Red River Ski Area ', latitude: 36.7062, longitude: -105.4129, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Riverside Hills ', latitude: 33.9331, longitude: -117.3763, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Rotarun ', latitude: 43.4974, longitude: -114.3651, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Royal Mountain ', latitude: 43.0813, longitude: -74.5048, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sandia Peak ', latitude: 35.2037, longitude: -106.4506, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Schweitzer Mountain ', latitude: 48.368, longitude: -116.6227, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Seven Springs Mountain Resort ', latitude: 40.023, longitude: -79.2977, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Shawnee Peak ', latitude: 44.059, longitude: -70.8155, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Showdown ', latitude: 46.8384, longitude: -110.7005, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sierra-at-Tahoe ', latitude: 38.8009, longitude: -120.0809, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Silver Creek Ski Area ', latitude: 38.4406, longitude: -79.9892, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Silver Mountain ', latitude: 47.5407, longitude: -116.1332, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Silverton Mountain ', latitude: 37.8846, longitude: -107.6659, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sipapu ', latitude: 36.1542, longitude: -105.5482, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sitzmark Lifts ', latitude: 48.8639, longitude: -119.1651, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Apache ', latitude: 33.3973, longitude: -105.7887, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Beech ', latitude: 36.1947, longitude: -81.878, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Big Bear ', latitude: 41.5233, longitude: -75.0251, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Bluewood ', latitude: 46.0825, longitude: -117.8512, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Bradford ', latitude: 42.7447, longitude: -71.0558, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Brule ', latitude: 46.0297, longitude: -88.7012, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Cloudcroft ', latitude: 32.9525, longitude: -105.709, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Cooper ', latitude: 39.3608, longitude: -106.3028, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Denton ', latitude: 46.0297, longitude: -88.7012, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Granby Ranch ', latitude: 40.0452, longitude: -105.906, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Gull ', latitude: 46.4476, longitude: -94.378, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Roundtop ', latitude: 40.1095, longitude: -76.9275, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Santa Fe ', latitude: 35.7963, longitude: -105.8024, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Snowstar ', latitude: 41.4253, longitude: -90.7462, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Sundown ', latitude: 41.8847, longitude: -72.9467, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Valley (closed)', latitude: 32.45222, longitude: -110.78389, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Ski Ward ', latitude: 42.3015, longitude: -71.683, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Skiland ', latitude: 65.0457, longitude: -147.4104, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sky Tavern Ski Area ', latitude: 39.3369, longitude: -119.8725, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sleeping Giant Ski Resort ', latitude: 44.4952, longitude: -109.9436, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sleepy Hollow Sports Park ', latitude: 41.5894, longitude: -93.5333, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: "Smugglers' Notch ", latitude: 44.5885, longitude: -72.79, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow Creek ', latitude: 39.4673, longitude: -94.9707, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow King Mountain ', latitude: 43.4736, longitude: -110.7558, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow Ridge Ski Resort ', latitude: 43.6397, longitude: -75.4201, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow Snake Ski & Golf ', latitude: 43.9591, longitude: -84.7809, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow Summit ', latitude: 34.2364, longitude: -116.8893, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow Trails Ski Resort ', latitude: 40.6729, longitude: -82.4985, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snow Valley ', latitude: 34.2249, longitude: -117.0362, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snowbasin ', latitude: 41.216, longitude: -111.8569, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snowbird ', latitude: 40.5818948, longitude: -111.6552, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snowhaven ', latitude: 45.8675, longitude: -116.0893, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snowmass', latitude: 39.1956, longitude: -106.9513, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snowshoe Mountain ', latitude: 38.4108, longitude: -79.9936, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Snowy Range ', latitude: 41.3412, longitude: -106.1835, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Soda Springs ', latitude: 42.6544, longitude: -111.6047, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Soldier Mountain ', latitude: 43.4855, longitude: -114.8294, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Solitude ', latitude: 40.6199, longitude: -111.5919, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Song Mountain Resort ', latitude: 42.7738, longitude: -76.1571, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Spirit Mountain ', latitude: 45.0582, longitude: -123.5814, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Spout Springs ', latitude: 45.7552, longitude: -118.0514, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Spring Mountain -Schwenksville', latitude: 40.2725, longitude: -75.4501, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Squaw Valley ', latitude: 39.1976, longitude: -120.2354, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Standing Rocks ', latitude: 45.7503, longitude: -101.2004, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Steamboat Ski Resort ', latitude: 40.4572, longitude: -106.8045, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Stevens Pass ', latitude: 47.7448, longitude: -121.089, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Storrs Hill ', latitude: 43.6352, longitude: -72.2521, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Stowe Mountain Resort ', latitude: 44.5291, longitude: -72.7773, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Stratton Mountain Resort ', latitude: 43.1134, longitude: -72.9081, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sugar Bowl ', latitude: 39.3004, longitude: -120.3334, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sugar Hill ', latitude: 34.1065, longitude: -84.0335, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sugar Mountain ', latitude: 36.1301, longitude: -81.8592, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sugarbush Resort ', latitude: 44.1359, longitude: -72.8944, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sugarloaf ', latitude: 45.0542, longitude: -70.3085, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Suicide Six ', latitude: 43.6651, longitude: -72.5433, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Summit Central', latitude: 47.4101, longitude: -121.4135, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Summit East', latitude: 47.3901, longitude: -121.3962, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Summit Ski Area ', latitude: 34.2364, longitude: -116.8893, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sun Valley ', latitude: 43.6971, longitude: -114.3517, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sunburst Ski Area ', latitude: 43.4939, longitude: -88.224, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sundance ', latitude: 44.4064, longitude: -104.3758, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sunday River ', latitude: 44.4734, longitude: -70.8569, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sundown Mountain ', latitude: 42.5163, longitude: -90.8186, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sunlight Ski Area ', latitude: 39.3998, longitude: -107.3388, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Sunrise Park Resort ', latitude: 33.9736, longitude: -109.564, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Swain ', latitude: 42.4766, longitude: -77.8551, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Swiss Valley Ski and Snowboard Area ', latitude: 41.9541, longitude: -85.8271, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Tahoe Donner Downhill ', latitude: 39.3541, longitude: -120.2594, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Taos Ski Valley ', latitude: 36.596, longitude: -105.4545, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Telluride Ski Resort ', latitude: 37.9129, longitude: -107.8382, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Tenney Mountain Ski Resort ', latitude: 43.73778, longitude: -71.78361, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Terry Peak ', latitude: 44.3275, longitude: -103.8352, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Teton Pass ', latitude: 47.9298, longitude: -112.811, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'The Summit at Snoqualmie ', latitude: 47.4204, longitude: -121.4211, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Timber Ridge Ski Area ', latitude: 42.3915, longitude: -85.7809, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Timberline Four Seasons Resort ', latitude: 39.0425, longitude: -79.399, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Timberline Lodge ', latitude: 45.3311, longitude: -121.711, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Titcomb Mountain ', latitude: 44.6497, longitude: -70.1704, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Titus Mountain ', latitude: 44.7666, longitude: -74.2329, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Treetops Resort ', latitude: 45.0331, longitude: -84.5892, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Triangle Sports Area ', latitude: 44.5101, longitude: -87.9508, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Trollhaugen ', latitude: 45.3513, longitude: -92.6181, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Turner Mountain ', latitude: 48.605, longitude: -115.6309, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Tussey Mountain Ski Area ', latitude: 40.7693, longitude: -77.754, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Tyrol Basin ', latitude: 43.046, longitude: -89.7805, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Vail Ski Resort ', latitude: 39.6061, longitude: -106.355, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wachusett Mountain ', latitude: 42.5029, longitude: -71.8863, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Warner Canyon ', latitude: 42.2369, longitude: -120.2941, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Waterville Valley Resort ', latitude: 43.9652, longitude: -71.5279, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Welch Village ', latitude: 44.5607, longitude: -92.7304, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'West Mountain ', latitude: 43.2856, longitude: -73.7253, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Whaleback ', latitude: 43.6017, longitude: -72.1803, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'White Pass ', latitude: 46.6374, longitude: -121.3913, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'White Pine ', latitude: 42.9778, longitude: -109.7587, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Whitecap Mountains ', latitude: 46.408, longitude: -90.3952, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Whiteface Mountain ', latitude: 44.3537, longitude: -73.8614, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Whitefish Mountain Resort ', latitude: 48.4831, longitude: -114.3582, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Whitetail Ridge ', latitude: 41.6121, longitude: -88.3696, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Whitetail Ski Resort ', latitude: 39.7418, longitude: -77.9333, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wild Mountain ', latitude: 45.4888, longitude: -92.7053, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wildcat Mountain ', latitude: 44.2641, longitude: -71.2394, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Willamette Pass ', latitude: 43.6007, longitude: -122.0365, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wilmot Mountain ', latitude: 42.499, longitude: -88.1877, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Windham Mountain ', latitude: 42.2937, longitude: -74.2567, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Winter Park Resort ', latitude: 39.8868, longitude: -105.7625, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wintergreen Resort ', latitude: 37.9149, longitude: -78.9438, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Winterplace ', latitude: 37.5957, longitude: -81.12, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wolf Creek ski area ', latitude: 37.4748, longitude: -106.7936, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Wolf Ridge ', latitude: 35.9548, longitude: -82.5088, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Yawgoo Valley ', latitude: 41.5176, longitude: -71.5273, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')
SkiArea.create(ski_area_name: 'Yellowstone Club ', latitude: 45.2458, longitude: -111.3745, address: 'Some address', pass: 'epic', site_url: 'www.someurl.com')